import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

const styles = StyleSheet.create({
  modal: { justifyContent: 'flex-end', margin: 0 },
  container: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    height: '80%',
  },
  contentArea: {
    flex: 1,
  },
  title: {
    fontSize: 18,
    fontFamily: 'PlayfairDisplay-SemiBold',
    color: colors.black,
  },
  modeRow: { flexDirection: 'row', gap: 8, marginVertical: 12 },
  modeButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  modeButtonActive: { borderColor: colors.heading, backgroundColor: '#FFF8EB' },
  modeText: { color: colors.black, fontFamily: 'Inter-Medium', fontSize: 12 },
  selectionArea: {
    flex: 1,
    minHeight: 180,
  },
  loadingArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  list: {
    flex: 1,
  },
  listContent: { paddingBottom: 8 },
  item: {
    borderWidth: 1,
    borderColor: '#EEE',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  itemActive: { borderColor: colors.heading, backgroundColor: '#FFF8EB' },
  itemTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  itemMainPress: {
    flex: 1,
    minWidth: 0,
  },
  itemExpandedPress: {
    marginTop: 0,
  },
  rowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginLeft: 8,
  },
  rowActionBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderColor,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowActionIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    tintColor: colors.darkGrey,
  },
  rowActionIconDelete: {
    tintColor: colors.darkGrey,
  },
  itemHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  itemTitle: {
    flex: 1,
    color: colors.black,
    fontFamily: 'Inter-Medium',
    fontSize: 14,
  },
  customBadge: {
    borderWidth: 1,
    borderColor: colors.borderColor,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: colors.white,
  },
  customBadgeText: {
    fontSize: 10,
    fontFamily: 'Inter-Medium',
    color: colors.darkGrey,
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  metaPill: {
    backgroundColor: '#F6F6F6',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  metaPillActive: {
    backgroundColor: colors.white,
  },
  metaPillText: {
    fontSize: 11,
    fontFamily: 'Inter-Medium',
    color: colors.green,
  },
  itemDescription: {
    marginTop: 8,
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    color: colors.darkGrey,
    lineHeight: 18,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  chip: {
    borderWidth: 1,
    borderColor: colors.borderColor,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: colors.white,
    maxWidth: '100%',
  },
  chipText: {
    fontSize: 11,
    fontFamily: 'Inter-Regular',
    color: colors.black,
  },
  equipmentLine: {
    marginTop: 6,
    fontSize: 11,
    fontFamily: 'Inter-Regular',
    color: colors.green,
  },
  summaryCard: {
    borderWidth: 1,
    borderColor: colors.heading,
    borderRadius: 12,
    backgroundColor: '#FFF8EB',
    padding: 12,
    marginBottom: 10,
  },
  summaryTitle: {
    fontSize: 15,
    fontFamily: 'PlayfairDisplay-Medium',
    color: colors.black,
    marginBottom: 6,
  },
  summaryDescription: {
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    color: colors.darkGrey,
    lineHeight: 18,
    marginTop: 6,
  },
  customWrap: { marginBottom: 12, gap: 10 },
  sectionLabel: {
    fontSize: 13,
    color: colors.darkGrey,
    fontFamily: 'Inter-Medium',
    marginBottom: 4,
  },
  sectionRow: { flexDirection: 'row', gap: 8, marginBottom: 4 },
  sectionChip: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: 'center',
  },
  sectionChipActive: {
    borderColor: colors.heading,
    backgroundColor: '#FFF8EB',
  },
  sectionChipText: {
    fontSize: 12,
    color: colors.black,
    fontFamily: 'Inter-Medium',
  },
  sectionChipTextActive: { color: colors.heading },
  bottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    justifyContent: 'space-between',
  },
  bottomRowGroup: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  label: {
    fontSize: 14,
    color: colors.darkGrey,
    fontFamily: 'Inter-Medium',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.black,
    fontFamily: 'Inter-Regular',
    marginBottom: 10,
  },
  durationInput: {
    width: 100,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: colors.black,
    fontFamily: 'Inter-Regular',
    textAlign: 'center',
  },
  errorText: { color: '#C62828', fontFamily: 'Inter-Regular', marginBottom: 8 },
  cancelBtn: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: colors.borderColor,
    borderRadius: 10,
  },
  cancelText: { color: colors.darkGrey, fontFamily: 'Inter-Medium' },
  saveBtn: {
    backgroundColor: colors.heading,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  saveText: { color: colors.white, fontFamily: 'Inter-SemiBold' },
  noticeBanner: {
    borderWidth: 1,
    borderColor: colors.heading,
    borderRadius: 10,
    backgroundColor: '#FFF8EB',
    padding: 12,
    marginBottom: 10,
  },
  noticeBannerText: {
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    color: colors.darkGrey,
    lineHeight: 18,
  },
  manageActionsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  manageEditBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.heading,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  manageEditText: {
    color: colors.heading,
    fontFamily: 'Inter-SemiBold',
    fontSize: 13,
  },
  manageDeleteBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#C62828',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  manageDeleteText: {
    color: '#C62828',
    fontFamily: 'Inter-SemiBold',
    fontSize: 13,
  },
});

export default styles;
