import { StyleSheet } from 'react-native';
import { fontSize } from '../../../constants/fonts';
import { colors } from '../../../constants/colors';
import { sizes } from '../../../constants/sizes';

export const partnerHomeStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.white,
  },
  scrollContent: {
    paddingHorizontal: sizes.screenWidth * 0.05,
    paddingBottom: 24,
    gap: 16,
  },
  header: {
    alignSelf: 'center',
    width: sizes.screenWidth * 0.9,
    paddingVertical: 12,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    width: sizes.screenWidth * 0.24,
    height: sizes.screenWidth * 0.1,
    resizeMode: 'contain',
  },
  profileButton: {
    borderRadius: 50,
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 4,
    paddingHorizontal: 6,
    gap: 6,
    backgroundColor: '#F0F0F0',
  },
  profileIcon: {
    height: 26,
    width: 26,
    resizeMode: 'contain',
  },
  profileButtonText: {
    fontSize: fontSize.Regular,
    color: colors.black,
    fontFamily: 'Inter-Regular',
  },
  contextLine: {
    marginTop: 6,
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    color: colors.green,
    textAlign: 'center',
  },
  contextName: {
    fontFamily: 'Inter-Medium',
  },
  phaseBody: {
    width: sizes.screenWidth * 0.82,
    alignItems: 'flex-start',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  rowBottom: {
    flexDirection: 'row',
    gap: 6,
  },
  rowFull: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  currentPhaseIconMain: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
  },
  heading: {
    color: colors.heading,
    fontFamily: 'PlayfairDisplay-SemiBold',
    fontSize: 22,
  },
  phaseTextContainer: {
    borderWidth: 1.5,
    borderColor: colors.heading,
    borderRadius: 50,
    paddingHorizontal: 12,
    marginTop: sizes.screenHeight * 0.01,
    marginBottom: sizes.screenHeight * 0.03,
    alignSelf: 'flex-start',
  },
  textPrimary: {
    fontSize: fontSize.regular,
    color: colors.heading,
    fontFamily: 'Inter-Regular',
  },
  colCenter: {
    alignItems: 'center',
    alignSelf: 'center',
    gap: 4,
  },
  spacedText: {
    fontSize: 12,
    color: colors.green,
    fontFamily: 'Inter-Light-BETA',
    letterSpacing: 3,
  },
  textBlackMedium: {
    fontSize: fontSize.medium,
    color: colors.black,
    fontFamily: 'Inter-Regular',
  },
  cyclePhaseCard: {
    width: sizes.screenWidth * 0.82,
    alignItems: 'flex-start',
    backgroundColor: colors.white,
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 12,
    marginVertical: 8,
  },
  numberTextMedium: {
    fontSize: 16,
    fontFamily: 'Inter-Regular',
    color: colors.green,
  },
  dayTextContainer: {
    paddingVertical: 1,
    paddingHorizontal: 10,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: '#D4D4D4',
  },
  progressIndicator: {
    width: '100%',
    height: 4,
    borderRadius: 3,
    backgroundColor: '#E4E4E4',
    marginBottom: 12,
    overflow: 'hidden',
  },
  progress: {
    height: '100%',
    borderRadius: 3,
  },
  textDarkGrey: {
    fontSize: 12,
    color: colors.darkGrey,
    fontFamily: 'Inter-Regular',
  },
  textBlackNormal: {
    fontSize: 14,
    color: colors.black,
    fontFamily: 'Inter-Regular',
  },
  babyDevelopmentText: {
    fontSize: 18,
    color: colors.heading,
    fontFamily: 'PlayfairDisplay-SemiBold',
    marginBottom: 8,
  },
  softCopyContainer: {
    backgroundColor: '#ECF0F6',
    width: sizes.screenWidth * 0.82,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 8,
  },
  heroLink: {
    marginTop: 12,
    fontFamily: 'Inter-SemiBold',
    fontSize: 13,
    color: '#E799AD',
    alignSelf: 'flex-start',
  },
  loadingBox: {
    padding: 24,
    alignItems: 'center',
    width: '100%',
  },
  container: {
    paddingHorizontal: 16,
    width: '100%',
  },
  container2: {
    paddingHorizontal: sizes.screenWidth * 0.04,
    paddingVertical: 16,
    borderWidth: 1.5,
    borderRadius: 16,
    borderColor: colors.borderColor,
    gap: 16,
  },
  sectionTitle: {
    fontSize: 15,
    fontFamily: 'PlayfairDisplay-SemiBold',
    color: colors.black,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardLink: {
    fontSize: 13,
    fontFamily: 'Inter-Medium',
    color: colors.heading,
  },
  symptomStatusText: {
    fontSize: 13,
    fontFamily: 'Inter-Medium',
    color: colors.black,
    marginTop: 2,
  },
  todaySymptomsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  symptomChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F8F8F8',
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  symptomChipName: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: colors.black,
  },
  symptomSeverityBadge: {
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  symptomSeverityText: {
    fontSize: 11,
    fontFamily: 'Inter-SemiBold',
    textTransform: 'capitalize',
  },
  symptomEmptyText: {
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    color: colors.darkGrey,
  },
  symptomSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 2,
    gap: 12,
  },
  symptomSummaryLabel: {
    fontSize: 13,
    fontFamily: 'Inter-Regular',
    color: colors.darkGrey,
  },
  symptomSummaryValue: {
    fontSize: 13,
    fontFamily: 'Inter-Medium',
    color: colors.black,
    flex: 1,
    textAlign: 'right',
  },
  sleepStatusText: {
    fontSize: 13,
    fontFamily: 'Inter-Medium',
    color: colors.black,
  },
  sleepSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 2,
    gap: 12,
  },
  sleepSummaryLabel: {
    fontSize: 13,
    fontFamily: 'Inter-Regular',
    color: colors.darkGrey,
  },
  sleepSummaryValue: {
    fontSize: 13,
    fontFamily: 'Inter-Medium',
    color: colors.black,
    flex: 1,
    textAlign: 'right',
  },
  sleepQualityBadge: {
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  sleepQualityBadgeText: {
    fontSize: 12,
    fontFamily: 'Inter-SemiBold',
  },
  sleepStreakPill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#FFF8EB',
    borderWidth: 1,
    borderColor: '#E4AF5D66',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sleepStreakText: {
    color: colors.heading,
    fontFamily: 'Inter-SemiBold',
    fontSize: 12,
  },
  fastingCard: {
    paddingHorizontal: 16,
    gap: 12,
    width: '100%',
  },
  fastingSectionTitle: {
    fontSize: 16,
    fontFamily: 'PlayfairDisplay-Medium',
    color: colors.black,
  },
  fastingStatusText: {
    fontSize: 13,
    color: colors.green,
    fontFamily: 'Inter-Regular',
    lineHeight: 20,
  },
  fastingTimer: {
    fontSize: 32,
    fontFamily: 'Inter-Bold',
    color: colors.black,
    letterSpacing: 1,
  },
  fastingGoalText: {
    fontSize: 12,
    color: colors.disabledText,
    fontFamily: 'Inter-Regular',
  },
  ritualsContainer: {
    paddingHorizontal: 16,
    width: '100%',
  },
  ritualsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    alignItems: 'center',
  },
  ritualsHeaderTitle: {
    fontSize: 18,
    fontFamily: 'PlayfairDisplay-SemiBold',
    color: colors.black,
  },
  ritualsHeaderProgress: {
    fontSize: 14,
    color: colors.green,
    fontFamily: 'Inter-Regular',
  },
  sectionHeading: {
    fontSize: 14,
    fontFamily: 'PlayfairDisplay-SemiBold',
    color: colors.green,
    marginTop: 10,
    marginBottom: 10,
    letterSpacing: 1,
  },
  ritualsSection: {
    gap: 20,
  },
  divider: {
    height: 1,
    backgroundColor: '#00000015',
    marginVertical: 15,
  },
  itemContainer: {
    gap: 6,
  },
  itemHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkIcon: {
    width: 18,
    height: 18,
  },
  itemTitle: {
    flex: 1,
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: colors.black,
  },
  itemTitleDone: {
    color: colors.disabledText,
    textDecorationLine: 'line-through',
  },
  tagText: {
    fontSize: 12,
    color: colors.green,
    fontFamily: 'Inter-Light',
  },
  itemDescription: {
    marginLeft: 24,
    fontSize: 12,
    color: colors.green,
    fontFamily: 'Inter-Regular',
  },
  ritualEmpty: {
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    color: colors.green,
  },
  exploreHeading: {
    color: colors.green,
    fontSize: 16,
    fontFamily: 'PlayfairDisplay-Medium',
    marginTop: 4,
    marginBottom: 4,
  },
  exploreCard: {
    backgroundColor: colors.white,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#f2f2f2',
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  exploreIconWrap: {
    backgroundColor: colors.lightOranger,
    borderRadius: 10,
    width: sizes.screenWidth * 0.1,
    height: sizes.screenWidth * 0.1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  exploreIcon: {
    resizeMode: 'contain',
    width: sizes.screenWidth * 0.05,
    height: sizes.screenWidth * 0.05,
  },
  exploreTitle: {
    color: colors.black,
    fontSize: 14,
    fontFamily: 'Inter-Regular',
  },
  exploreSubtitle: {
    color: colors.green,
    fontSize: 12,
    fontFamily: 'Inter-Regular',
  },
  exploreArrow: {
    tintColor: colors.green,
    resizeMode: 'contain',
    width: sizes.screenWidth * 0.03,
    height: sizes.screenWidth * 0.03,
  },
  exitModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: sizes.screenWidth * 0.08,
  },
  exitModalCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.borderColor,
  },
  exitModalTitle: {
    fontFamily: 'PlayfairDisplay-SemiBold',
    fontSize: 18,
    color: colors.heading,
    marginBottom: 8,
  },
  exitModalMessage: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    color: colors.disabledText,
    lineHeight: 20,
    marginBottom: 20,
  },
  exitModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  exitModalCancelButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderColor,
  },
  exitModalCancelText: {
    fontFamily: 'Inter-Medium',
    fontSize: 14,
    color: colors.heading,
  },
  exitModalConfirmButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: colors.heading,
    minWidth: 72,
    alignItems: 'center',
  },
  exitModalConfirmText: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 14,
    color: colors.white,
  },
  exitModalButtonDisabled: {
    opacity: 0.5,
  },
});
